name: MinecraftGPT
version: '1.3-SNAPSHOT'
main: tech.lukinhas.minecraftgpt.Main
api-version: '1.20'
commands:
  minecraftgpt:
    description: MinecraftGPT Command
    usage: /minecraftgpt <subcommand>
    aliases: mcgpt
