name: MinecraftGPT
version: '1.4-SNAPSHOT'
main: tech.lukinhas.minecraftgpt.Main
commands:
  minecraftgpt:
    description: MinecraftGPT Command
    usage: /minecraftgpt <subcommand>
    aliases: mcgpt
